### ISSUE TITLE
hi sir, when you do its bug free? are you working on it?

### ISSUE THREAD

**Issue by Naresh95375** [ngtien137/Audio-Wave-View#2]
which type of bug ?

**Comment by ngtien137** [comment]
Yeah. I'm still doing it, but not often. You can clone repository then test it. About bugs, you can leave feedback here

**Comment by Naresh95375** [comment]
sir, can i modify library according to my use.....?

**Comment by ngtien137** [comment]
Yes. Use as you want. You don't need ask me for the permission. This's a open source library

**Comment by Naresh95375** [comment]
sir, i need your help... i am stuck in one place in development
can you help me for find solution for my problem?
i am find solution for multi track for video and audio same as your library 
check below photo
can you suggest me any this for this?
any library for this?

i need help for design side and i have solution for backend side

**Comment by ngtien137** [comment]
For loading image preview of video, you can use MediaMetadataRetriever (Example as my library: https://github.com/ngtien137/Basic-Video-Cut-Bar)
For loading sample of audio such as AudioWaveView, you can find key word: "WaveFormView android".
Then learn something about custom view and manging touch to move your view:
https://developer.android.com/training/gestures/viewgroup

**Comment by Naresh95375** [comment]
okay sir. thank you 
i can do following thing
For loading image preview of video, you can use MediaMetadataRetriever (Example as my library: https://github.com/ngtien137/Basic-Video-Cut-Bar)
For loading sample of audio such as AudioWaveView, you can find key word: "WaveFormView android".


but i not know any thing about this
Then learn something about custom view and manging touch to move your view:
https://developer.android.com/training/gestures/viewgroup

in your this library possible to both can fit in movable object ?

**Comment by ngtien137** [comment]
In my opinion, you need draw your own CustomViewGroup. It's divided into two part: Audio and video. And you need knowledge about manging touch for moving them correctly.

**Comment by Naresh95375** [comment]
okay sir, thank you for your help

**Comment by Naresh95375** [comment]
render problem

Dimension "-11" in attribute "awv_thumb_progress_static_position" is missing unit!

![photo_2021-03-24_16-51-11](https://user-images.githubusercontent.com/55321122/112302849-8dc4e500-8cc1-11eb-9eb5-31b549dc0365.jpg)
