### ISSUE TITLE
render problem in xml

### ISSUE THREAD

**Issue by Naresh95375** [ngtien137/Audio-Wave-View#3]
render problem
![photo_2021-03-24_16-51-11](https://user-images.githubusercontent.com/55321122/112310151-3ecf7d80-8cca-11eb-99b9-418f46b51397.jpg)

Dimension "-11" in attribute "awv_thumb_progress_static_position" is missing unit!

**Comment by ngtien137** [comment]
-11 is not the value of that property. You need pass left or center value. It's the position of the progress when you use static mode position. Static progress mode set progress thumb to a specific position and the flexible mode set progress thumb like a thumb of seekbar

**Comment by ngtien137** [comment]
But i don't think it can use with all of value, i just work with center value for my project

**Comment by Naresh95375** [comment]
I am also doing for the center

https://user-images.githubusercontent.com/55321122/112415753-682fee00-8d4a-11eb-8781-285d776ec390.MOV

. pls, check the video.

**Comment by ngtien137** [comment]
awv_thumb_progress_static_position is only use for static_mode progress

**Comment by ngtien137** [comment]
when you use flexible mode, progress can moving as a thumb of seekbar

**Comment by Naresh95375** [comment]
okay done
