### ISSUE TITLE
audio wave view issue when activity open again

### ISSUE THREAD

**Issue by Naresh95375** [ngtien137/Audio-Wave-View#4]
step by step
1) open audio list activity
2) selet audio and open audio trim activity ( work good )
3) but when press back so goto audio select activity
4) now select audio again and open audio trim activity
5) audio wave view not render

https://user-images.githubusercontent.com/55321122/112315828-848f4480-8cd0-11eb-8af7-f2e0fe76ac54.MOV

**Comment by Naresh95375** [comment]
same issue when debug app and open first time

**Comment by ngtien137** [comment]
My demo is working good. I think you should check view when inititalize. You need call setAudioPath function after view initialized. You need call it inside post function because when activity just showed up, view's width and height are zero
audioView.post {
    audioView.setAudioPath(...)
}

**Comment by Naresh95375** [comment]
problem solve

 audioWaveView.post(new Runnable() {

                    @Override
                    public void run() {
                        audioWaveView.setAudioPath(srcFile);
                    }
                });
